config/routes.rb
Rails.application.routes.draw do
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root "static#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  include ActiveRecord::Bitemporal
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
      @bitemporal = User.find_by_sql(["SELECT * FROM users WHERE bitemporal_id = :bid ORDER BY created_at DESC, valid_to DESC", { bid: params[:id] }])
      @bitemporal_ignore_valid_datetime = User.ignore_valid_datetime.where(bitemporal_id:params[:id] ).order(valid_from: :desc)
      @bitemporal_within_deleted = User.within_deleted.where(bitemporal_id:params[:id] ).order(valid_from: :desc)[1..-1]
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :avatar, :profile, :email, :twitter, :github)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def column_changed(orig, target, name)
    return unless target
    orig.send(name) != target.send(name)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Minitrue</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="robots" content="noindex">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="dark:bg-gray-700">
    <div class="container mx-auto">
      <div class="px-16 py-16">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/users/_bitemporal.html.erb
<div class="flex text-xs dark:text-gray-200">
  <div class="p-2  bg-green-100 dark:bg-green-900 rounded-full shadow-md">ignore_valid_datetime</div>
  <div class="ml-4 p-2 bg-red-100 dark:bg-red-900 rounded-full shadow-md">within_deleted</div>
</div>
<table class="table-auto dark:text-gray-200 border-separate">
  <thead>
    <tr>
      <th class="px-4 py-2">name</th>
      <th class="px-4 py-2">avatar</th>
      <th class="px-4 py-2">profile</th>
      <th class="px-4 py-2">email</th>
      <th class="px-4 py-2">twitter</th>
      <th class="px-4 py-2">github</th>
      <th class="px-4 py-2">valid_from</th>
      <th class="px-4 py-2">valid_to</th>
      <th class="px-4 py-2">transaction_from</th>
      <th class="px-4 py-2">transaction_to</th>
      <th class="px-4 py-2">created_at</th>
      <th class="px-4 py-2">updated_at</th>
    </tr>
  </thead>
  <tbody class="text-xs">
  <% bitemporal.each_with_index do |btm, i| %>
    <% if i != 0 %>
      <% ignore_datetime = bitemporal_ignore_valid_datetime.find { |d| d.id_in_database == btm.id_in_database } ? "bg-green-100 dark:bg-green-900" : nil %>
      <% deleted = bitemporal_within_deleted.find { |d| d.id_in_database == btm.id_in_database } ? "bg-red-100 dark:bg-red-900" : nil %>
    <% end%>

    <% if i == 0 || ignore_datetime %>
      <% prev_index = bitemporal_ignore_valid_datetime.find_index { |d| d.id_in_database == btm.id_in_database }&.+ 1 %>
      <% prev = prev_index ? bitemporal_ignore_valid_datetime[prev_index] : nil %>
      <% change_style = "border-8 border-blue-500"%>
    <% end%>
    <tr class="<%= deleted %> <%= ignore_datetime %>">
      <td class="border px-2 py-2 <%= column_changed(btm, prev, :name) ? change_style : "" %>"><%= btm.name %></td>
      <td class="border px-2 py-2 <%= column_changed(btm, prev, :avatar) ? change_style : "" %>"><img src="<%= btm.avatar %>"></td>
      <td class="border px-2 py-2 <%= column_changed(btm, prev, :profile) ? change_style : "" %>"><%= btm.profile %></td>
      <td class="border px-2 py-2 <%= column_changed(btm, prev, :email) ? change_style : "" %>"><%= btm.email %></td>
      <td class="border px-2 py-2 <%= column_changed(btm, prev, :twitter) ? change_style : "" %>"><%= btm.twitter %></td>
      <td class="border px-2 py-2 <%= column_changed(btm, prev, :github) ? change_style : "" %>"><%= btm.github %></th>
      <td class="border px-2 py-2"><%= btm.valid_from %></td>
      <td class="border px-2 py-2"><%= btm.valid_to %></td>
      <td class="border px-2 py-2"><%= btm.transaction_from %></td>
      <td class="border px-2 py-2"><%= btm.transaction_to %></td>
      <td class="border px-2 py-2"><%= btm.created_at %></td>
      <td class="border px-2 py-2"><%= btm.updated_at %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-4 relative">
    <%= form.label :name, class: "text-gray-200" %>
    <%= form.text_field :name, class: "rounded-lg border-transparent flex-1 appearance-none border border-gray-300 w-full py-2 px-4 bg-white text-gray-700 placeholder-gray-400 shadow-sm text-base focus:outline-none focus:ring-2 focus:ring-purple-600 focus:border-transparent" %>
  </div>

  <div class="mb-4 relative">
    <%= form.label :avatar, class: "text-gray-200" %>
    <%= form.text_field :avatar, class: "rounded-lg border-transparent flex-1 appearance-none border border-gray-300 w-full py-2 px-4 bg-white text-gray-700 placeholder-gray-400 shadow-sm text-base focus:outline-none focus:ring-2 focus:ring-purple-600 focus:border-transparent" %>
  </div>

  <div class="mb-4 relative">
    <%= form.label :profile, class: "text-gray-200" %>
    <%= form.text_field :profile, class: "rounded-lg border-transparent flex-1 appearance-none border border-gray-300 w-full py-2 px-4 bg-white text-gray-700 placeholder-gray-400 shadow-sm text-base focus:outline-none focus:ring-2 focus:ring-purple-600 focus:border-transparent" %>
  </div>

  <div class="mb-4 relative">
    <%= form.label :email, class: "text-gray-200" %>
    <%= form.text_field :email, class: "rounded-lg border-transparent flex-1 appearance-none border border-gray-300 w-full py-2 px-4 bg-white text-gray-700 placeholder-gray-400 shadow-sm text-base focus:outline-none focus:ring-2 focus:ring-purple-600 focus:border-transparent" %>
  </div>

  <div class="mb-4 relative">
    <%= form.label :twitter, class: "text-gray-200" %>
    <%= form.text_field :twitter, class: "rounded-lg border-transparent flex-1 appearance-none border border-gray-300 w-full py-2 px-4 bg-white text-gray-700 placeholder-gray-400 shadow-sm text-base focus:outline-none focus:ring-2 focus:ring-purple-600 focus:border-transparent" %>
  </div>

  <div class="mb-4 relative">
    <%= form.label :github, class: "text-gray-200" %>
    <%= form.text_field :github, class: "rounded-lg border-transparent flex-1 appearance-none border border-gray-300 w-full py-2 px-4 bg-white text-gray-700 placeholder-gray-400 shadow-sm text-base focus:outline-none focus:ring-2 focus:ring-purple-600 focus:border-transparent" %>
  </div>

  <div class="mb-4 relative">
    <%= form.submit new ? "Create" : "Update", class: "py-2 px-4  bg-indigo-600 hover:bg-indigo-700 focus:ring-indigo-500 focus:ring-offset-indigo-200 text-white w-full transition ease-in duration-200 text-center text-base font-semibold shadow-md focus:outline-none focus:ring-2 focus:ring-offset-2  rounded-lg" %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div class="p-4 shadow-lg rounded-2xl bg-white dark:bg-gray-800 p-4 w-64">
    <div class="text-center mb-4 opacity-90">
      <img alt="avatar" src="<%= user.avatar %>" class="mx-auto object-cover rounded-full h-40 w-40 "/>
    </div>
    <div class="text-center">
        <p class="text-2xl text-gray-800 dark:text-white">
          <%= user.name %>
        </p>
        <p class="text-md text-gray-500 dark:text-gray-400 max-w-xs py-4 font-light">
          <%= user.profile %>
        </p>
    </div>
    <div class="pt-2 flex border-t border-gray-200 w-44 mx-auto text-gray-500 items-center justify-center">
        <a href="https://twitter.com/<%= user.twitter %>">
            <svg width="30" height="30" fill="currentColor" class="mx-2 text-xl hover:text-gray-800 dark:hover:text-white transition-colors duration-200" viewBox="0 0 1792 1792" xmlns="http://www.w3.org/2000/svg">
                <path d="M1684 408q-67 98-162 167 1 14 1 42 0 130-38 259.5t-115.5 248.5-184.5 210.5-258 146-323 54.5q-271 0-496-145 35 4 78 4 225 0 401-138-105-2-188-64.5t-114-159.5q33 5 61 5 43 0 85-11-112-23-185.5-111.5t-73.5-205.5v-4q68 38 146 41-66-44-105-115t-39-154q0-88 44-163 121 149 294.5 238.5t371.5 99.5q-8-38-8-74 0-134 94.5-228.5t228.5-94.5q140 0 236 102 109-21 205-78-37 115-142 178 93-10 186-50z">
                </path>
            </svg>
        </a>
        <a href="https://github.com/<%= user.github %>">
            <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="mx-2 text-xl hover:text-gray-800 dark:hover:text-white transition-colors duration-200" viewBox="0 0 1792 1792">
                <path d="M896 128q209 0 385.5 103t279.5 279.5 103 385.5q0 251-146.5 451.5t-378.5 277.5q-27 5-40-7t-13-30q0-3 .5-76.5t.5-134.5q0-97-52-142 57-6 102.5-18t94-39 81-66.5 53-105 20.5-150.5q0-119-79-206 37-91-8-204-28-9-81 11t-92 44l-38 24q-93-26-192-26t-192 26q-16-11-42.5-27t-83.5-38.5-85-13.5q-45 113-8 204-79 87-79 206 0 85 20.5 150t52.5 105 80.5 67 94 39 102.5 18q-39 36-49 103-21 10-45 15t-57 5-65.5-21.5-55.5-62.5q-19-32-48.5-52t-49.5-24l-20-3q-21 0-29 4.5t-5 11.5 9 14 13 12l7 5q22 10 43.5 38t31.5 51l10 23q13 38 44 61.5t67 30 69.5 7 55.5-3.5l23-4q0 38 .5 88.5t.5 54.5q0 18-13 30t-40 7q-232-77-378.5-277.5t-146.5-451.5q0-209 103-385.5t279.5-279.5 385.5-103zm-477 1103q3-7-7-12-10-3-13 2-3 7 7 12 9 6 13-2zm31 34q7-5-2-16-10-9-16-3-7 5 2 16 10 10 16 3zm30 45q9-7 0-19-8-13-17-6-9 5 0 18t17 7zm42 42q8-8-4-19-12-12-20-3-9 8 4 19 12 12 20 3zm57 25q3-11-13-16-15-4-19 7t13 15q15 6 19-6zm63 5q0-13-17-11-16 0-16 11 0 13 17 11 16 0 16-11zm58-10q-2-11-18-9-16 3-14 15t18 8 14-14z">
                </path>
            </svg>
        </a>
    </div>
</div>

app/views/users/edit.html.erb
<h1 class="text-gray-200">Editing user</h1>

<div class="container mx-auto">
  <%= render "form", user: @user %>
</div>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<div id="users" class="container flex flex-row flex-wrap gap-4"> 
  <% @users.each do |user| %>
    <div class="relative">
      <%= render user %>
      <p class="absolute top-0 right-0 mt-6 mr-6">
        <%= link_to user do %>
          <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" class="text-xl hover:text-gray-800 dark:hover:text-white transition-colors duration-200">
          <path d="M20 14.66V20a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h5.34">
          </path><polygon points="18 2 22 6 12 16 8 16 8 12 18 2"></polygon></svg>
        <% end%>
      </p>
    </div>
  <% end %>
  <div class="self-center">
    <%= link_to new_user_path, class: "flex items-center p-4  transition ease-in duration-200 uppercase rounded-full hover:bg-gray-800 hover:text-white border-2 border-gray-900 focus:outline-none" do %>
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="12" y1="5" x2="12" y2="19"></line><line x1="5" y1="12" x2="19" y2="12"></line></svg>
      Add new user
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user, new: true %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<% if notice %>
  <div class="bg-green-200 border-green-600 text-green-600 border-l-4 p-4 mb-8" role="alert">
      <p class="font-bold">
          Success
      </p>
      <p>
         <%= notice %>
      </p>
  </div>
<% end %>

<div class="pb-8 dark:text-gray-200">
  <p><%= link_to "<<Users", users_path %></p>
</div>


<div class="flex justify-around">
  <div>
    <%= render @user %>
  </div>
  <div class="px-8">
    <%= render "form", user: @user %>
  </div>
</div>

<div class="absolute left-0 p-4 overflow-x-scroll overflow-y-scroll max-width-100vw">
  <h1 class="text-gray-200">Bitemporal data table</h2>
  <%= render "bitemporal", bitemporal: @bitemporal, bitemporal_within_deleted: @bitemporal_within_deleted, bitemporal_ignore_valid_datetime: @bitemporal_ignore_valid_datetime %>
</div>